name: IOT DEVICE ANDROID INTEGRATION

on:
  workflow_run:
    workflows: [ "IOT DEVICE ANDROID DEBUG CI" ]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Integration
        run: |
          git clone https://$GIT_ACCESS_TOKEN@github.com/archurcode/Integrationtesting.git
          bash .github/scripts/integration/updateVersionCodeForIntegration.sh
        env:
          GIT_ACCESS_TOKEN: ${{ secrets.IOT_GITHUB_ACCESS_TOKEN }}
      - name: Build with Gradle
        run: |
          cd Integrationtesting
          ./gradlew build

